# Generated by Django 4.2.1 on 2023-06-06 12:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("nekretnina", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("prezime", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefon", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="NekretninaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                ("povrsina", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("opis", wagtail.fields.RichTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kupovina", "Kupovina"),
                            ("prodaja", "Prodaja"),
                            ("iznajmljivanje", "Iznajmljivanje"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "slika",
                    models.ImageField(blank=True, null=True, upload_to="nekretnine/"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nekretnine_page",
                        to="nekretnina.agent",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Nekretnina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naziv", models.CharField(max_length=255)),
                ("povrsina", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("opis", wagtail.fields.RichTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kupovina", "Kupovina"),
                            ("prodaja", "Prodaja"),
                            ("iznajmljivanje", "Iznajmljivanje"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nekretnine",
                        to="nekretnina.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KontaktForma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("poruka", models.TextField()),
                (
                    "nekretnina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakt_forme",
                        to="nekretnina.nekretnina",
                    ),
                ),
            ],
        ),
    ]
