# Generated by Django 4.2.1 on 2023-06-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0003_agentpage"),
    ]

    operations = [
        migrations.DeleteModel(name="AgentPage",),
    ]
