# Generated by Django 4.2.1 on 2023-06-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("nekretnina", "0005_agentindexpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("prezime", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefon", models.CharField(max_length=20)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
