# Generated by Django 4.2.1 on 2023-06-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0009_alter_nekretninapage_agent"),
    ]

    operations = [
        migrations.RemoveField(model_name="agentpage", name="email",),
        migrations.RemoveField(model_name="agentpage", name="ime",),
        migrations.RemoveField(model_name="agentpage", name="prezime",),
        migrations.RemoveField(model_name="agentpage", name="telefon",),
        migrations.AddField(
            model_name="agentpage",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nekretnina.agent",
            ),
        ),
    ]
