# Generated by Django 4.2.1 on 2023-06-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0010_remove_agentpage_email_remove_agentpage_ime_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretninapage", name="agent",),
        migrations.RemoveField(model_name="nekretninapage", name="cena",),
        migrations.RemoveField(model_name="nekretninapage", name="naziv",),
        migrations.RemoveField(model_name="nekretninapage", name="opis",),
        migrations.RemoveField(model_name="nekretninapage", name="povrsina",),
        migrations.RemoveField(model_name="nekretninapage", name="slika",),
        migrations.RemoveField(model_name="nekretninapage", name="status",),
        migrations.AddField(
            model_name="nekretninapage",
            name="nekretnina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nekretnine_page",
                to="nekretnina.nekretnina",
            ),
        ),
    ]
