# Generated by Django 4.2.1 on 2023-06-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0011_remove_nekretninapage_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretninapage",
            name="nekretnina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nekretnina.nekretnina",
            ),
        ),
    ]
