# Generated by Django 4.2.1 on 2023-06-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0012_alter_nekretninapage_nekretnina"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktformaformfield", name="page",),
        migrations.RemoveField(model_name="kontaktformapage", name="page_ptr",),
        migrations.DeleteModel(name="KontaktForma",),
        migrations.DeleteModel(name="KontaktFormaFormField",),
        migrations.DeleteModel(name="KontaktFormaPage",),
    ]
