# Generated by Django 4.2.1 on 2023-06-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0013_remove_kontaktformaformfield_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NekretninaPageWithForm",
            fields=[
                (
                    "nekretninapage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="nekretnina.nekretninapage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("nekretnina.nekretninapage",),
        ),
    ]
