# Generated by Django 4.2.1 on 2023-06-07 12:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0015_kontaktformaformfield_kontaktformapage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("poruka", models.TextField()),
                (
                    "datum_vrijeme",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nekretnina.agent",
                    ),
                ),
                (
                    "nekretnina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nekretnina.nekretnina",
                    ),
                ),
            ],
        ),
    ]
