# Generated by Django 4.2.1 on 2023-06-07 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nekretnina", "0016_inbox"),
    ]

    operations = [
        migrations.RemoveField(model_name="inbox", name="datum_vrijeme",),
        migrations.RemoveField(model_name="inbox", name="email",),
        migrations.RemoveField(model_name="inbox", name="ime",),
        migrations.RemoveField(model_name="inbox", name="poruka",),
        migrations.AddField(
            model_name="inbox",
            name="korisnik",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
