# Generated by Django 4.2.1 on 2023-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0017_remove_inbox_datum_vrijeme_remove_inbox_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktformaformfield", name="page",),
        migrations.RemoveField(model_name="kontaktformapage", name="nekretnina",),
        migrations.RemoveField(model_name="kontaktformapage", name="page_ptr",),
        migrations.DeleteModel(name="Inbox",),
        migrations.DeleteModel(name="KontaktFormaFormField",),
        migrations.DeleteModel(name="KontaktFormaPage",),
    ]
