# Generated by Django 4.2.1 on 2023-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0019_kontaktforma"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slika", models.ImageField(upload_to="nekretnine_slike/")),
            ],
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="vrsta_nekretnine",
            field=models.CharField(
                choices=[
                    ("kuca", "Kuća"),
                    ("stan", "Stan"),
                    ("vikendica", "Vikendica"),
                    ("garsonjera", "Garsonjera"),
                ],
                default="stan",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="galerija_slika",
            field=models.ManyToManyField(to="nekretnina.slika"),
        ),
    ]
