# Generated by Django 4.2.1 on 2023-06-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0020_slika_nekretnina_vrsta_nekretnine_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="galerija_slika",),
        migrations.DeleteModel(name="Slika",),
    ]
