# Generated by Django 4.2.1 on 2023-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0021_remove_nekretnina_galerija_slika_delete_slika"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="slika",
            field=models.ImageField(
                default="nekretnine_slike/berza.jpg", upload_to="nekretnine_slike/"
            ),
        ),
    ]
