# Generated by Django 4.2.1 on 2023-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0022_nekretnina_slika"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="galerija_slika",
            field=models.ManyToManyField(blank=True, to="nekretnina.nekretnina"),
        ),
    ]
