# Generated by Django 4.2.1 on 2023-06-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0023_nekretnina_galerija_slika"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretninaindexpage",
            name="slika_modela",
            field=models.ImageField(
                default="nekretnine_slike/placeholder.jpg",
                upload_to="nekretnine_slike/",
            ),
        ),
    ]
