# Generated by Django 4.2.1 on 2023-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0024_nekretninaindexpage_slika_modela"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="vrsta_nekretnine",
            field=models.CharField(
                choices=[
                    ("kuca", "Kuća"),
                    ("stan", "Stan"),
                    ("vikendica", "Vikendica"),
                    ("garsonjera", "Garsonjera"),
                    ("poslovni_prostor", "Poslovni_prostor"),
                ],
                default="stan",
                max_length=35,
            ),
        ),
    ]
