# Generated by Django 4.2.1 on 2023-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0026_remove_nekretninaindexpage_slika_modela_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nekretnina", old_name="vrsta_nekretnine", new_name="vrsta",
        ),
    ]
