# Generated by Django 4.2.1 on 2023-06-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0027_rename_vrsta_nekretnine_nekretnina_vrsta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slika", models.ImageField(upload_to="galerija_slika/")),
            ],
        ),
        migrations.AlterField(
            model_name="nekretnina", name="opis", field=models.TextField(),
        ),
        migrations.DeleteModel(name="KontaktForma",),
        migrations.AlterField(
            model_name="nekretnina",
            name="galerija_slika",
            field=models.ManyToManyField(
                related_name="nekretnine", to="nekretnina.slika"
            ),
        ),
    ]
