# Generated by Django 4.2.1 on 2023-06-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0029_kontaktforma_delete_slika_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="KontaktForma",),
    ]
