# Generated by Django 4.2.1 on 2023-06-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0030_delete_kontaktforma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina", name="opis", field=models.TextField(),
        ),
        migrations.CreateModel(
            name="KontaktForma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("poruka", models.TextField()),
                (
                    "nekretnina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakti",
                        to="nekretnina.nekretnina",
                    ),
                ),
            ],
        ),
    ]
