# Generated by Django 4.2.1 on 2023-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0031_alter_nekretnina_opis_kontaktforma"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktforma", name="nekretnina",),
        migrations.RemoveField(model_name="kontaktforma", name="poruka",),
        migrations.AddField(
            model_name="agent",
            name="inbox",
            field=models.ManyToManyField(to="nekretnina.kontaktforma"),
        ),
    ]
