# Generated by Django 4.2.1 on 2023-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0032_remove_kontaktforma_nekretnina_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktforma", name="email",),
        migrations.AddField(
            model_name="kontaktforma",
            name="poruka",
            field=models.CharField(default="nema", max_length=700),
        ),
    ]
