# Generated by Django 4.2.1 on 2023-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0033_remove_kontaktforma_email_kontaktforma_poruka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="inbox",
            field=models.ManyToManyField(blank=True, to="nekretnina.kontaktforma"),
        ),
    ]
