# Generated by Django 4.2.1 on 2023-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0034_alter_agent_inbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="bazen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="dvoriste",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="garaza",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(default="Banja Luka", max_length=100),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="lokacija",
            field=models.CharField(default="centar", max_length=255),
        ),
    ]
