# Generated by Django 4.2.1 on 2023-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0035_nekretnina_bazen_nekretnina_dvoriste_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="bazen",),
        migrations.RemoveField(model_name="nekretnina", name="dvoriste",),
        migrations.RemoveField(model_name="nekretnina", name="garaza",),
        migrations.RemoveField(model_name="nekretnina", name="grad",),
        migrations.RemoveField(model_name="nekretnina", name="lokacija",),
        migrations.AddField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[("banjaluka", "Banja Luka"), ("okolina", "Okolina")],
                default="banjaluka",
                max_length=15,
            ),
        ),
    ]
