# Generated by Django 4.2.1 on 2023-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0037_nekretnina_lokacija"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="lokacija",
            field=models.CharField(
                choices=[
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("novavaros", "Nova Varos"),
                    ("borik", "Borik"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
    ]
