# Generated by Django 4.2.1 on 2023-06-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0038_alter_nekretnina_lokacija"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="lokacija",
            field=models.CharField(
                choices=[
                    ("", "Sve"),
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("novavaros", "Nova Varos"),
                    ("borik", "Borik"),
                    ("cokori", "Cokorska Polja"),
                    ("slatina", "Slatina"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("", "Sve"),
                    ("banjaluka", "Banja Luka"),
                    ("okolina", "Okolina"),
                ],
                default="banjaluka",
                max_length=15,
            ),
        ),
    ]
