# Generated by Django 4.2.1 on 2023-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0039_alter_nekretnina_lokacija_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="lokacija",),
        migrations.RemoveField(model_name="nekretnina", name="mjesto",),
        migrations.AddField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(
                choices=[("banjaluka", "Banja Luka"), ("okolina", "okolina")],
                default="banjaluka",
                max_length=15,
            ),
        ),
    ]
