# Generated by Django 4.2.1 on 2023-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nekretnina",
            "0040_remove_nekretnina_lokacija_remove_nekretnina_mjesto_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("borik", "Borik"),
                    ("novavaros", "Nova Varos"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(
                choices=[("banjaluka", "Banja Luka"), ("okolina", "Okolina")],
                default="banjaluka",
                max_length=15,
            ),
        ),
    ]
