# Generated by Django 4.2.1 on 2023-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0041_nekretnina_mjesto_alter_nekretnina_grad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(
                choices=[("banjaluka", "Banja Luka"), ("okolina", "okolina")],
                default="banjaluka",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("borik", "Borik"),
                    ("novavaros", "Nova Varos"),
                    ("cokori", "Cokorska Polja"),
                    ("slatina", "slatina"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
    ]
