# Generated by Django 4.2.1 on 2023-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0043_alter_nekretnina_grad_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[("cokori", "Cokorska Polja"), ("slatina", "Slatina")],
                default="cokori",
                max_length=15,
            ),
        ),
    ]
