# Generated by Django 4.2.1 on 2023-06-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0045_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("borik", "Borik"),
                    ("novavaros", "Nova Varos"),
                    ("cokori", "Cokorska Polja"),
                    ("slatina", "Slatina"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
    ]
