# Generated by Django 4.2.1 on 2023-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0047_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(default="centar", max_length=15),
        ),
    ]
