# Generated by Django 4.2.1 on 2023-06-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0048_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(
                choices=[
                    ("svi", "Svi"),
                    ("banjaluka", "Banja Luka"),
                    ("okolina", "Okolina"),
                ],
                default="svi",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("centar", "Centar"),
                    ("mejdan", "Mejdan"),
                    ("borik", "Borik"),
                    ("novavaros", "Nova Varos"),
                ],
                max_length=15,
            ),
        ),
    ]
