# Generated by Django 4.2.1 on 2023-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0049_alter_nekretnina_grad_alter_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="grad",
            field=models.CharField(
                choices=[("banjaluka", "Banja Luka"), ("okolina", "Okolina")],
                default="banjaluka",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(choices=[], default="mejdan", max_length=15),
        ),
    ]
