# Generated by Django 4.2.1 on 2023-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0051_remove_nekretnina_mjesto_alter_nekretnina_grad"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="mjesto",
            field=models.CharField(
                choices=[
                    ("mejdan", "Mejdan"),
                    ("centar", "Centar"),
                    ("borik", "Borik"),
                    ("laus", "Laus"),
                    ("cokori", "Cokori"),
                    ("slatina", "Slatina"),
                ],
                default="centar",
                max_length=15,
            ),
        ),
    ]
