# Generated by Django 4.2.1 on 2023-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0053_alter_nekretnina_grad"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="mjesto",),
        migrations.AlterField(
            model_name="nekretnina",
            name="status",
            field=models.CharField(
                choices=[
                    ("mejdan", "Mejdan"),
                    ("centar", "Centar"),
                    ("borik", "Borik"),
                    ("laus", "Laus"),
                    ("cokori", "Cokori"),
                    ("slatina", "Slatina"),
                ],
                max_length=15,
            ),
        ),
    ]
