# Generated by Django 4.2.1 on 2023-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0055_nekretnina_mjesto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="status",
            field=models.CharField(
                choices=[
                    ("kupovina", "Kupovina"),
                    ("prodaja", "Prodaja"),
                    ("iznajmljivanje", "Iznajmljivanje"),
                ],
                max_length=15,
            ),
        ),
    ]
