# Generated by Django 4.2.1 on 2023-06-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0056_alter_nekretnina_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="dvoriste",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="garaza",
            field=models.BooleanField(default=False),
        ),
    ]
