# Generated by Django 4.2.1 on 2023-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0057_nekretnina_dvoriste_nekretnina_garaza"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="bazen",
            field=models.BooleanField(default=False),
        ),
    ]
