# Generated by Django 4.2.1 on 2023-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0059_kontaktforma_naziv_nekretnine"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="centalno_grijanje",
            field=models.BooleanField(default=False),
        ),
    ]
