# Generated by Django 4.2.1 on 2023-06-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0061_nekretnina_lift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nekretnina",
            old_name="centalno_grijanje",
            new_name="centralno_grijanje",
        ),
    ]
