# Generated by Django 4.2.1 on 2023-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0062_rename_centalno_grijanje_nekretnina_centralno_grijanje"),
    ]

    operations = [
        migrations.AddField(
            model_name="nekretnina",
            name="klima",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="parking",
            field=models.BooleanField(default=False),
        ),
    ]
