# Generated by Django 4.2.1 on 2023-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nekretnina",
            "0064_remove_nekretnina_galerija_slika_nekretnina_slika1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Korisnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("sifra", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("odobren", models.BooleanField(default=False)),
            ],
        ),
    ]
