# Generated by Django 4.2.1 on 2023-06-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0065_korisnik"),
    ]

    operations = [
        migrations.RenameField(
            model_name="korisnik", old_name="odobren", new_name="odobreno",
        ),
    ]
