# Generated by Django 4.2.1 on 2023-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0066_rename_odobren_korisnik_odobreno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="korisnik",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="korisnik",
            name="ime",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
