# Generated by Django 4.2.1 on 2023-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0070_agent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="korisnik",
            name="inbox",
            field=models.ManyToManyField(blank=True, to="nekretnina.kontaktforma"),
        ),
    ]
