# Generated by Django 4.2.1 on 2023-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0072_kontaktforma_odgovor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kontaktforma",
            name="odgovor",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
