# Generated by Django 4.2.1 on 2023-06-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0073_alter_kontaktforma_odgovor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kontaktforma", old_name="poruka", new_name="upit",
        ),
        migrations.RemoveField(model_name="kontaktforma", name="odgovor",),
        migrations.CreateModel(
            name="Poruke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("tekst", models.CharField(default="nema", max_length=700)),
                (
                    "forma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poruke",
                        to="nekretnina.kontaktforma",
                    ),
                ),
            ],
        ),
    ]
