# Generated by Django 4.2.1 on 2023-06-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0074_rename_poruka_kontaktforma_upit_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktforma", name="naziv_nekretnine",),
    ]
