# Generated by Django 4.2.1 on 2023-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0079_remove_kontaktforma_naziv_nekretnine"),
    ]

    operations = [
        migrations.AddField(
            model_name="kontaktforma",
            name="naziv_nekretnine",
            field=models.CharField(default="da", max_length=255),
        ),
    ]
