# Generated by Django 4.2.1 on 2023-06-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0080_kontaktforma_naziv_nekretnine"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktforma", name="naziv_nekretnine",),
    ]
