# Generated by Django 4.2.1 on 2023-06-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0085_alter_kontaktforma_naziv_nekretnine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kontaktforma",
            name="naziv_nekretnine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kontakt_forme",
                to="nekretnina.nekretnina",
            ),
        ),
    ]
