# Generated by Django 4.2.1 on 2023-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0089_remove_kontaktforma_ime_agenta_kontaktforma_agenta"),
    ]

    operations = [
        migrations.RemoveField(model_name="kontaktforma", name="agenta",),
        migrations.AddField(
            model_name="kontaktforma",
            name="ime_agenta",
            field=models.CharField(default="007", max_length=255),
        ),
    ]
