# Generated by Django 4.2.1 on 2023-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0090_remove_kontaktforma_agenta_kontaktforma_ime_agenta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nekretnina",
            name="naziv",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
