# Generated by Django 4.2.1 on 2023-06-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("nekretnina", "0091_alter_nekretnina_naziv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent", name="sifra", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="kontaktforma",
            name="upit",
            field=models.CharField(max_length=700),
        ),
        migrations.RemoveField(model_name="nekretnina", name="slika",),
        migrations.AlterField(
            model_name="nekretnina",
            name="slika1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nekretnina_slike1",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="slika2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nekretnina_slike2",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="slika3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nekretnina_slike3",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="nekretnina",
            name="slika4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nekretnina_slike4",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="poruke", name="tekst", field=models.CharField(max_length=700),
        ),
        migrations.AddField(
            model_name="nekretnina",
            name="slika",
            field=models.ManyToManyField(
                blank=True, related_name="nekretnina_slike", to="wagtailimages.image"
            ),
        ),
    ]
