# Generated by Django 4.2.1 on 2023-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nekretnina", "0092_alter_agent_sifra_alter_kontaktforma_upit_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="slika",),
        migrations.AddField(
            model_name="nekretnina",
            name="slika",
            field=models.ImageField(blank=True, upload_to="nekretnina_slike"),
        ),
    ]
