# Generated by Django 4.2.1 on 2023-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("nekretnina", "0093_remove_nekretnina_slika_nekretnina_slika"),
    ]

    operations = [
        migrations.RemoveField(model_name="nekretnina", name="slika",),
        migrations.RemoveField(model_name="nekretnina", name="slika1",),
        migrations.RemoveField(model_name="nekretnina", name="slika2",),
        migrations.RemoveField(model_name="nekretnina", name="slika3",),
        migrations.RemoveField(model_name="nekretnina", name="slika4",),
        migrations.AddField(
            model_name="nekretnina",
            name="slike",
            field=models.ManyToManyField(
                blank=True, related_name="nekretnina_slike", to="wagtailimages.image"
            ),
        ),
    ]
