# Generated by Django 4.2.1 on 2023-06-21 10:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BookingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("naziv", models.CharField(max_length=255, unique=True)),
                ("povrsina", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("opis", wagtail.fields.RichTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kupovina", "Kupovina"),
                            ("prodaja", "Prodaja"),
                            ("iznajmljivanje", "Iznajmljivanje"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "vrsta",
                    models.CharField(
                        choices=[
                            ("kuca", "Kuća"),
                            ("stan", "Stan"),
                            ("vikendica", "Vikendica"),
                            ("garsonjera", "Garsonjera"),
                            ("poslovni_prostor", "Poslovni prostor"),
                        ],
                        default="stan",
                        max_length=35,
                    ),
                ),
                (
                    "grad",
                    models.CharField(
                        choices=[("banjaluka", "Banja Luka"), ("okolina", "Okolina")],
                        default="banjaluka",
                        max_length=15,
                    ),
                ),
                (
                    "mjesto",
                    models.CharField(
                        choices=[
                            ("mejdan", "Mejdan"),
                            ("centar", "Centar"),
                            ("borik", "Borik"),
                            ("laus", "Laus"),
                            ("cokori", "Cokori"),
                            ("slatina", "Slatina"),
                        ],
                        default="centar",
                        max_length=15,
                    ),
                ),
                ("dvoriste", models.BooleanField(default=False)),
                ("garaza", models.BooleanField(default=False)),
                ("bazen", models.BooleanField(default=False)),
                ("centralno_grijanje", models.BooleanField(default=False)),
                ("lift", models.BooleanField(default=False)),
                ("parking", models.BooleanField(default=False)),
                ("klima", models.BooleanField(default=False)),
                ("slike", models.ManyToManyField(to="wagtailimages.image")),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
