# Generated by Django 4.2.1 on 2023-06-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_remove_agentpage_agent_agentpage_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage",
            name="agent",
            field=models.ForeignKey(
                default="007",
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.agentpage",
            ),
        ),
    ]
