# Generated by Django 4.2.1 on 2023-06-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_bookingpage_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nekretnine",
                to="booking.agentpage",
            ),
        ),
    ]
