# Generated by Django 4.2.1 on 2023-06-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0009_alter_bookingpage_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="KontaktForma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("upit", models.CharField(max_length=700)),
                ("naziv_nekretnine", models.CharField(max_length=255)),
                ("ime_agenta", models.CharField(default="007", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Poruke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=255)),
                ("tekst", models.CharField(max_length=700)),
                (
                    "forma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poruke",
                        to="booking.kontaktforma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Korisnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="kevin", max_length=255, unique=True),
                ),
                ("sifra", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("odobreno", models.BooleanField(default=False)),
                (
                    "inbox",
                    models.ManyToManyField(blank=True, to="booking.kontaktforma"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
