# Generated by Django 4.2.1 on 2023-06-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_kontaktforma_poruke_korisnik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="korisnik",
            name="odobreno",
            field=models.BooleanField(default=True),
        ),
    ]
