# Generated by Django 4.2.1 on 2023-06-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_korisnik_odobreno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nekretnina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nekretnina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.bookingpage",
                    ),
                ),
            ],
        ),
    ]
