# Generated by Django 4.2.1 on 2023-06-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_nekretnina"),
    ]

    operations = [
        migrations.DeleteModel(name="Nekretnina",),
    ]
