# Generated by Django 4.2.1 on 2023-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_delete_nekretnina"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="inbox",
            field=models.ManyToManyField(blank=True, to="booking.kontaktforma"),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_agent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bookingpage",
            name="opis",
            field=models.TextField(default="Opiss"),
        ),
        migrations.AlterField(
            model_name="korisnik",
            name="odobreno",
            field=models.BooleanField(default=False),
        ),
    ]
