# Generated by Django 4.2.1 on 2023-06-28 09:28

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_bookingpage_slike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage", name="opis", field=wagtail.fields.RichTextField(),
        ),
    ]
