# Generated by Django 4.2.1 on 2023-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_alter_bookingpage_opis"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="orjentacija",
            field=models.CharField(
                choices=[
                    ("Lijeva obala Vrbasa", "lijeva_obala_vrbasa"),
                    ("Desna obala Vrbasa", "desna_obala_vrbasa"),
                    ("5 min od centra", "10_min_od_centra"),
                    ("10 min od Kastela", "10_min_od_kastela"),
                    ("5 min od K4", "5_min_od_k4"),
                    ("10 min od kampusa", "10_min_od_kampusa"),
                    ("5 min od UKC-a", "5_min_od_ukc"),
                    ("Blizu parka", "blizu_parka"),
                    ("Blizu zelenog Mosta", "blizu_zelenog_mosta"),
                ],
                default="desna_obala_vrbasa",
                max_length=35,
            ),
        ),
    ]
