# Generated by Django 4.2.1 on 2023-06-30 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("booking", "0018_bookingpage_orjentacija"),
    ]

    operations = [
        migrations.CreateModel(
            name="KorisnikPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("sifra", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("odobreno", models.BooleanField(default=False)),
                (
                    "inbox",
                    models.ManyToManyField(blank=True, to="booking.kontaktforma"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
