# Generated by Django 4.2.1 on 2023-06-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_korisnikpage"),
    ]

    operations = [
        migrations.DeleteModel(name="KorisnikPage",),
    ]
