# Generated by Django 4.2.1 on 2023-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_delete_korisnikpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="odobreno",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="korisnik",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agent",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="korisnik",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="korisnik",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
