# Generated by Django 4.2.1 on 2023-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_agent_odobreno_korisnik_is_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agentpage",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="agentpage",
            name="sifra",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="agentpage",
            name="telefon",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="agentpage",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="kontaktforma",
            name="ime_agenta",
            field=models.CharField(max_length=255),
        ),
    ]
