# Generated by Django 4.2.1 on 2023-07-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_bookingpage_latitude_bookingpage_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="image",
            field=models.ImageField(default="stan.jpg", upload_to="booking/images/"),
        ),
    ]
