# Generated by Django 4.2.1 on 2023-07-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_bookingpage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage",
            name="image",
            field=models.ImageField(default="stan.jpg", upload_to="images/"),
        ),
    ]
