# Generated by Django 4.2.1 on 2023-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_alter_bookingpage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
