# Generated by Django 4.2.1 on 2023-07-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0028_bookingpage_image_bookingpage_slike_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpage",
            name="image",
            field=models.ImageField(default="stan.jpg", upload_to="images/"),
        ),
    ]
