# Generated by Django 4.2.1 on 2023-07-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0029_alter_bookingpage_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingpage", name="image",),
        migrations.RemoveField(model_name="bookingpage", name="slike",),
        migrations.DeleteModel(name="BookingPageGalleryImage",),
    ]
