# Generated by Django 4.2.1 on 2023-07-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0031_bookingpage_image_bookingpage_slike_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingpage", name="slike",),
    ]
