# Generated by Django 4.2.1 on 2023-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("booking", "0034_remove_bookingpage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                through="booking.BookingPageGalleryImage",
                to="wagtailimages.image",
            ),
        ),
    ]
