# Generated by Django 4.2.1 on 2023-07-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0035_bookingpage_images"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingpage", name="images",),
    ]
