# Generated by Django 4.2.1 on 2023-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0037_bookingpage_slike"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingpage", name="slike",),
        migrations.AddField(
            model_name="bookingpage",
            name="slike",
            field=models.ImageField(default="stan.jog", upload_to="original_images/"),
        ),
    ]
