# Generated by Django 4.2.1 on 2023-07-22 10:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("booking", "0038_remove_bookingpage_slike_bookingpage_slike"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingKategorija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={"verbose_name_plural": "blog categories",},
        ),
        migrations.AddField(
            model_name="bookingpage",
            name="kategorije",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="booking.bookingkategorija"
            ),
        ),
    ]
