# Generated by Django 4.2.1 on 2023-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0039_bookingkategorija_bookingpage_kategorije"),
    ]

    operations = [
        migrations.CreateModel(
            name="Karakteristika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(model_name="bookingpage", name="kategorije",),
        migrations.DeleteModel(name="BookingKategorija",),
    ]
