# Generated by Django 4.2.3 on 2023-07-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0046_rename_name_karakteristika_ime_rename_name_tip_ime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="karakteristika", old_name="ime", new_name="name",
        ),
        migrations.RenameField(model_name="tip", old_name="ime", new_name="name",),
    ]
