# Generated by Django 4.2.3 on 2023-08-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0049_remove_bookingpage_karakteristika_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="karakteristika",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_page",
                to="booking.karakteristika",
            ),
        ),
    ]
