# Generated by Django 4.2.3 on 2023-08-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0050_bookingpage_karakteristika"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookingpage", name="karakteristika",),
        migrations.AddField(
            model_name="bookingpage",
            name="karakteristika",
            field=models.ManyToManyField(
                default=1, related_name="booking_page", to="booking.karakteristika"
            ),
        ),
    ]
