# Generated by Django 4.2.3 on 2023-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0052_tip_karakteristika_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpage",
            name="tip",
            field=models.ManyToManyField(
                default=1, related_name="booking_page", to="booking.tip"
            ),
        ),
    ]
