# Generated by Django 4.2.3 on 2023-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0053_bookingpage_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karakteristika",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
