# Generated by Django 4.2.3 on 2023-08-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0054_alter_karakteristika_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="korisnik",
            name="odobreno",
            field=models.BooleanField(default=True),
        ),
    ]
