# Generated by Django 4.2.3 on 2023-08-21 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0055_alter_korisnik_odobreno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="slug",
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
