<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-20 21:22
=======
<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-20 21:22
=======
# Generated by Django 4.2.2 on 2023-06-05 21:13
>>>>>>> f2079d21f8d69e5e8c102949a7b7ea2cda6ff006
>>>>>>> origin/master

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
